---
- name: Configurar servidor Kubernetes base
  hosts: k8s
  become: true

  tasks:

    - name: Actualizar apt
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar paquetes base
      apt:
        name:
          - openssh-server
          - ca-certificates
          - curl
          - git
          - jq 
          - gettext-base 
          - gnupg
          - lsb-release
        state: present

    - name: Habilitar y arrancar SSH
      service:
        name: ssh
        state: started
        enabled: yes

    # =========================
    # INSTALACIÓN DOCKER
    # =========================

    - name: Agregar clave GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Agregar repositorio Docker
      apt_repository:
        repo: >
          deb [arch=amd64]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Habilitar Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Asegurar que el grupo docker exista
      group:
        name: docker
        state: present

    - name: Agregar usuario al grupo docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # - name: Agregar usuario al grupo docker por comando
    #   command: >
    #     sudo groupadd docker && sudo usermod -aG docker $USER &&  newgrp docker

    # =========================
    # CONFIGURAR LOGS DOCKER
    # =========================

    - name: Configurar logging driver json-file
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
        owner: root
        group: root
        mode: '0644'
      notify: Restart docker

    # =========================
    # INSTALAR KUBECTL
    # =========================

    - name: Descargar kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    # =========================
    # INSTALAR K3D
    # =========================

    - name: Descargar script oficial de instalación de k3d
      get_url:
        url: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
        dest: /tmp/install_k3d.sh
        mode: '0755'

    - name: Ejecutar script de instalación de k3d
      command: /tmp/install_k3d.sh
      args:
        creates: /usr/local/bin/k3d

    - name: Crear cluster k3d dev
      command: >
        k3d cluster create dev
        --servers 1
        --agents 1
        -p 80:80@loadbalancer
        -p 8080:8080@loadbalancer
     # when: "'dev' not in k3d_clusters.stdout"

    - name: Crear kubeconfig del clsuter
      command: >
        mkdir -p ~/.kube && k3d kubeconfig get dev > ~/.kube/config 

    - name: get Repo kubernetes
      command: >
        git clone https://github.com/codeparce/kubernetes.git

  handlers:
    - name: Restart docker
      service:
        name: docker
        state: restarted