Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.provision "shell", inline: <<-SHELL
    useradd -m -s /bin/bash admin
    echo "admin:admin123" | chpasswd
    usermod -aG sudo admin
    echo "admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  SHELL

  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.56.10"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    node1.vm.provision "shell", inline: <<-SHELL
      useradd -m -s /bin/bash admin
      echo "admin:admin123" | chpasswd
      usermod -aG sudo admin
      echo "admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    SHELL

  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.56.11"
    node2.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    node2.vm.provision "shell", inline: <<-SHELL
      useradd -m -s /bin/bash admin
      echo "admin:admin123" | chpasswd
      usermod -aG sudo admin
      echo "admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    SHELL

  end

  config.vm.define "node3" do |node3|
    node3.vm.hostname = "node3"
    node3.vm.network "private_network", ip: "192.168.56.12"
    node3.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    node3.vm.provision "shell", inline: <<-SHELL
      useradd -m -s /bin/bash admin
      echo "admin:admin123" | chpasswd
      usermod -aG sudo admin
      echo "admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    SHELL

  end



end
