- name: Crear carpeta de prueba
  hosts: nodes
  become: true

  tasks:
    - name: Crear carpeta /tmp/ansible_test
      file:
        path: /tmp/ansible_test
        state: directory

    - name: Crear archivo /tmp/archivo_test.txt
      copy:
        dest: /tmp/mensaje.txt
        content: "Hola, esto es un archivo creado con Ansible"
        
    - name: Verificar si Docker está instalado
      command: docker --version
      register: docker_check
      ignore_errors: true

    - name: Instalar Docker solo si no está
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: true
      when: docker_check.failed